name: issue@auto-close-stale

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write

jobs:
  auto-close-stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 7
          stale-issue-label: stale
          stale-issue-message: ""
          close-issue-message: "This issue has been automatically closed due to 14 days of inactivity; feel free to reopen it if necessary."
